Docker : Fix incompatibility between Sphinx and docutils
This was causing the following error when building the documentation :

```
Exception occurred:
  File "/usr/lib/python2.7/site-packages/docutils/writers/_html_base.py", line 736, in depart_document
    assert not self.context, 'len(context) = %s' % len(self.context)
AssertionError: len(context) = 1
```